// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ServiceClient is the client API for ContactsService service.
type ServiceClient interface {
	SendFinalResult(ctx context.Context, in *FinalResult, opts ...grpc.CallOption) (*Empty, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func Client(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SendFinalResult(ctx context.Context, in *FinalResult, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/contacts.ContactsService/SendFinalResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactsServiceServer is the server API for ContactsService service.
type ContactsServiceServer interface {
	SendFinalResult(context.Context, *FinalResult) (*Empty, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) SendFinalResult(context.Context, *FinalResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFinalResult not implemented")
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ContactsServiceServer) {
	s.RegisterService(&ContactsService_ServiceDesc, srv)
}

func _Service_SendFinalResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServiceServer).SendFinalResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contacts.ContactsService/SendFinalResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServiceServer).SendFinalResult(ctx, req.(*FinalResult))
	}
	return interceptor(ctx, in, info, handler)
}

// ContactsService_ServiceDesc is the grpc.ServiceDesc for ContactsService service.
var ContactsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contacts.ContactsService",
	HandlerType: (*ContactsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFinalResult",
			Handler:    _Service_SendFinalResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contacts.proto",
}

