// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ContactsClient is the client API for ContactsService service.
type ContactsClient interface {
	SendContacts(ctx context.Context, in *Result, opts ...grpc.CallOption) (*Empty, error)
}

type contactsClient struct {
	cc grpc.ClientConnInterface
}

func Client(cc grpc.ClientConnInterface) ContactsClient {
	return &contactsClient{cc}
}

func (c *contactsClient) SendContacts(ctx context.Context, in *Result, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/contacts.ContactsService/SendContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactsServer is the server API for ContactsService service.
type ContactsServer interface {
	SendContacts(context.Context, *Result) (*Empty, error)
}

// UnimplementedServer can be embedded to have forward compatible implementations.
type UnimplementedServer struct{}

func (UnimplementedServer) SendContacts(context.Context, *Result) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendContacts not implemented")
}

func RegisterServer(s grpc.ServiceRegistrar, srv ContactsServer) {
	s.RegisterService(&Contacts_Desc, srv)
}

func _Service_SendContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).SendContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contacts.ContactsService/SendContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).SendContacts(ctx, req.(*Result))
	}
	return interceptor(ctx, in, info, handler)
}

// Contacts_Desc is the grpc.ServiceDesc for ContactsService service.
var Contacts_Desc = grpc.ServiceDesc{
	ServiceName: "contacts.ContactsService",
	HandlerType: (*ContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendContacts",
			Handler:    _Service_SendContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contacts.proto",
}

