// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: svc_config.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_GetBotConfig_FullMethodName     = "/svcpb.ConfigService/GetBotConfig"
	ConfigService_GetUserMasterKey_FullMethodName = "/svcpb.ConfigService/GetUserMasterKey"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService — gRPC service for inter-service communication with Landing.
// Authorization: metadata header "x-service-key" must contain the service key
// stored in app_config under "svc.service_key".
type ConfigServiceClient interface {
	// GetBotConfig returns decrypted Telegram bot settings.
	GetBotConfig(ctx context.Context, in *GetBotConfigRequest, opts ...grpc.CallOption) (*BotConfigResponse, error)
	// GetUserMasterKey returns the decrypted User MasterKey from Landing's in-memory cache.
	// The key is available only after the user has logged in at least once since the last
	// Landing restart. Returns codes.Unavailable if the key is not in cache.
	// The caller is responsible for deciding how to handle the unavailable case.
	GetUserMasterKey(ctx context.Context, in *GetUserMasterKeyRequest, opts ...grpc.CallOption) (*UserMasterKeyResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetBotConfig(ctx context.Context, in *GetBotConfigRequest, opts ...grpc.CallOption) (*BotConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetBotConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetUserMasterKey(ctx context.Context, in *GetUserMasterKeyRequest, opts ...grpc.CallOption) (*UserMasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMasterKeyResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetUserMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService — gRPC service for inter-service communication with Landing.
// Authorization: metadata header "x-service-key" must contain the service key
// stored in app_config under "svc.service_key".
type ConfigServiceServer interface {
	// GetBotConfig returns decrypted Telegram bot settings.
	GetBotConfig(context.Context, *GetBotConfigRequest) (*BotConfigResponse, error)
	// GetUserMasterKey returns the decrypted User MasterKey from Landing's in-memory cache.
	// The key is available only after the user has logged in at least once since the last
	// Landing restart. Returns codes.Unavailable if the key is not in cache.
	// The caller is responsible for deciding how to handle the unavailable case.
	GetUserMasterKey(context.Context, *GetUserMasterKeyRequest) (*UserMasterKeyResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetBotConfig(context.Context, *GetBotConfigRequest) (*BotConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetUserMasterKey(context.Context, *GetUserMasterKeyRequest) (*UserMasterKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMasterKey not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetBotConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetBotConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetBotConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetBotConfig(ctx, req.(*GetBotConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetUserMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetUserMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetUserMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetUserMasterKey(ctx, req.(*GetUserMasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svcpb.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBotConfig",
			Handler:    _ConfigService_GetBotConfig_Handler,
		},
		{
			MethodName: "GetUserMasterKey",
			Handler:    _ConfigService_GetUserMasterKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc_config.proto",
}
