// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: svc_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBotConfigRequest — empty request (auth via metadata).
type GetBotConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotConfigRequest) Reset() {
	*x = GetBotConfigRequest{}
	mi := &file_svc_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotConfigRequest) ProtoMessage() {}

func (x *GetBotConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBotConfigRequest) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{0}
}

// BotConfigResponse — Telegram bot settings.
type BotConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                    // Bot API token
	BotName       string                 `protobuf:"bytes,2,opt,name=bot_name,json=botName,proto3" json:"bot_name,omitempty"` // Bot username (without @)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotConfigResponse) Reset() {
	*x = BotConfigResponse{}
	mi := &file_svc_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotConfigResponse) ProtoMessage() {}

func (x *BotConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotConfigResponse.ProtoReflect.Descriptor instead.
func (*BotConfigResponse) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{1}
}

func (x *BotConfigResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BotConfigResponse) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

// GetUserMasterKeyRequest — request for a user's MasterKey.
type GetUserMasterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMasterKeyRequest) Reset() {
	*x = GetUserMasterKeyRequest{}
	mi := &file_svc_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMasterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMasterKeyRequest) ProtoMessage() {}

func (x *GetUserMasterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMasterKeyRequest.ProtoReflect.Descriptor instead.
func (*GetUserMasterKeyRequest) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserMasterKeyRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserMasterKeyResponse — raw 32-byte AES-256 MasterKey.
// Transmitted only over secured internal network (Docker bridge + service key auth).
type UserMasterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     []byte                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"` // 32 bytes — AES-256 key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMasterKeyResponse) Reset() {
	*x = UserMasterKeyResponse{}
	mi := &file_svc_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMasterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMasterKeyResponse) ProtoMessage() {}

func (x *UserMasterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMasterKeyResponse.ProtoReflect.Descriptor instead.
func (*UserMasterKeyResponse) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{3}
}

func (x *UserMasterKeyResponse) GetMasterKey() []byte {
	if x != nil {
		return x.MasterKey
	}
	return nil
}

// HealthRequest — пустой запрос для проверки доступности сервиса.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_svc_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{4}
}

// HealthResponse — статус сервиса.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // "ok" | "degraded"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // версия Landing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_svc_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_svc_config_proto protoreflect.FileDescriptor

const file_svc_config_proto_rawDesc = "" +
	"\n" +
	"\x10svc_config.proto\x12\x05svcpb\"\x15\n" +
	"\x13GetBotConfigRequest\"D\n" +
	"\x11BotConfigResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bbot_name\x18\x02 \x01(\tR\abotName\"2\n" +
	"\x17GetUserMasterKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"6\n" +
	"\x15UserMasterKeyResponse\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\fR\tmasterKey\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xe8\x01\n" +
	"\rConfigService\x12D\n" +
	"\fGetBotConfig\x12\x1a.svcpb.GetBotConfigRequest\x1a\x18.svcpb.BotConfigResponse\x12P\n" +
	"\x10GetUserMasterKey\x12\x1e.svcpb.GetUserMasterKeyRequest\x1a\x1c.svcpb.UserMasterKeyResponse\x12?\n" +
	"\x10GetServiceHealth\x12\x14.svcpb.HealthRequest\x1a\x15.svcpb.HealthResponseB,Z*github.com/ikermy/AiR_Common/pkg/bff/protob\x06proto3"

var (
	file_svc_config_proto_rawDescOnce sync.Once
	file_svc_config_proto_rawDescData []byte
)

func file_svc_config_proto_rawDescGZIP() []byte {
	file_svc_config_proto_rawDescOnce.Do(func() {
		file_svc_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_config_proto_rawDesc), len(file_svc_config_proto_rawDesc)))
	})
	return file_svc_config_proto_rawDescData
}

var file_svc_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_svc_config_proto_goTypes = []any{
	(*GetBotConfigRequest)(nil),     // 0: svcpb.GetBotConfigRequest
	(*BotConfigResponse)(nil),       // 1: svcpb.BotConfigResponse
	(*GetUserMasterKeyRequest)(nil), // 2: svcpb.GetUserMasterKeyRequest
	(*UserMasterKeyResponse)(nil),   // 3: svcpb.UserMasterKeyResponse
	(*HealthRequest)(nil),           // 4: svcpb.HealthRequest
	(*HealthResponse)(nil),          // 5: svcpb.HealthResponse
}
var file_svc_config_proto_depIdxs = []int32{
	0, // 0: svcpb.ConfigService.GetBotConfig:input_type -> svcpb.GetBotConfigRequest
	2, // 1: svcpb.ConfigService.GetUserMasterKey:input_type -> svcpb.GetUserMasterKeyRequest
	4, // 2: svcpb.ConfigService.GetServiceHealth:input_type -> svcpb.HealthRequest
	1, // 3: svcpb.ConfigService.GetBotConfig:output_type -> svcpb.BotConfigResponse
	3, // 4: svcpb.ConfigService.GetUserMasterKey:output_type -> svcpb.UserMasterKeyResponse
	5, // 5: svcpb.ConfigService.GetServiceHealth:output_type -> svcpb.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_config_proto_init() }
func file_svc_config_proto_init() {
	if File_svc_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_config_proto_rawDesc), len(file_svc_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_config_proto_goTypes,
		DependencyIndexes: file_svc_config_proto_depIdxs,
		MessageInfos:      file_svc_config_proto_msgTypes,
	}.Build()
	File_svc_config_proto = out.File
	file_svc_config_proto_goTypes = nil
	file_svc_config_proto_depIdxs = nil
}
